language: go

env:
  - GO111MODULE=on

install:
  - go mod vendor

matrix:
  include:
    - go: 1.19.x
      script:
        - go get -u golang.org/x/lint/golint
        - make lint
        - make vet
        - make test
    - go: 1.18.x
      script:
      - make test
    - go: 1.17.x
      script:
      - make test
    - go: 1.16.x
      script:
      - make test
    - go: 1.15.x
      script:
      - make test
    - go: 1.14.x
      script:
      - make test
    - go: 1.13.x
      script:
        - make test
    - go: 1.12.x
      script:
        - make test
    - go: 1.11.x
      script:
        - make test
